### ISSUE TITLE
Custom Tflite Model Usage

### ISSUE THREAD

**Issue by PriyaSoneji** [FIRST-Tech-Challenge/FtcRobotController#10]
We have created a custom tflite model with Tensorflow 2 and are running into issues with utilizing it. We tried to use it with the existing tfod object detector and got an error stating that we're using a newer model than what tfod accepts. Can you confirm what version you are using and what are our options for using Tensorflow 2?

**Comment by ssysm** [comment]
You might want to use a `MobileNet` model, if you are using a floating-point model, you need to specify `isModelQuantized` to `false` in the `tfodParameters`.
