### ISSUE TITLE
ftcsdk bintray sunset

### ISSUE THREAD

**Issue by PeterJohnson** [FIRST-Tech-Challenge/FtcRobotController#104]
Bintray is sunsetting on May 1: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

Currently the ftcsdk is hosted on bintray, so project builds will break starting May 1.

**Comment by NoahAndrews** [comment]
The next release will migrate the FTC libraries off of Bintray.

**Comment by JIceberg** [comment]
Can I ask what exactly y'all are migrating to?

**Comment by cmacfarl** [comment]
maven central

**Comment by NoahAndrews** [comment]
Version 6.2 is out, using Maven Central instead of Bintray.
