### ISSUE TITLE
No 5G wifi after Control Hub Operating System update to 1.1.2

### ISSUE THREAD

**Issue by GongInvaders** [FIRST-Tech-Challenge/FtcRobotController#123]
Moto E5 play unable to see 5G wifi Robot control after updating to Control Hub 1.1.2

**Comment by NoahAndrews** [comment]
That's very odd. If you have a Windows computer, please install the REV Hardware Client, connect your Control Hub to the computer via USB-C, select it in the client, click "Send Diagnostic Data to REV", and fill out the form. That will help us figure out what's going on.

**Comment by GongInvaders** [comment]
Data sent
