### ISSUE TITLE
Tensorflow setZoom only zooms in centre of image

### ISSUE THREAD

**Issue by Eeshwar-Krishnan** [FIRST-Tech-Challenge/FtcRobotController#142]
Currently the behaviour of the setZoom function is the zoom into the centre of the image. Obviously, zoom is a useful aspect of tensorflow given its internal resize to 300x300. However, zooming into the centre of the image is not always desired behaviour, because the area of interest in an image may not be in the centre for some robots, meaning teams have to physically move the camera to keep the area of interest in the center. The ability to offset the zoom, so that the user can zoom into a particular area of the camera would allow greater flexibility in using the API. If possible, if the area could be changed on the go, it could let teams be able to dynamically select where to zoom in.

**Comment by Windwoes** [comment]
TensorFlow is now removed from the SDK
