### ISSUE TITLE
Old repository should be archived

### ISSUE THREAD

**Issue by David10238** [FIRST-Tech-Challenge/FtcRobotController#146]
The old repository wasn't accepted new issues, so I'm posting here. The old repository located at https://github.com/FIRST-Tech-Challenge/ftc_app, should probably be archived and the README.md should be updated to link to this repository. Occasionally the community Discord has a team who accidentally downloaded the old repository.

**Comment by cmacfarl** [comment]
The repository you reference was a fork of the original ftc_app repository.  The downstream fork hadn't been updated with the contents of it's upstream parent which is indeed archived.  That's been fixed.  Thanks for pointing it out.
