### ISSUE TITLE
Android Studio Compile of 6.0 controller app fails

### ISSUE THREAD

**Issue by Crossle86** [FIRST-Tech-Challenge/FtcRobotController#154]
There is probably a simple answer for this, but just getting back into FTC after months away. Opened my 6.0 controller project expecting to work with that to get going again while waiting for 2021/2022 release. However, I cannot compile anything as all imports of org.firstinspires.ftc.robotcore packages fail with Cannot resolve symbol 'robotcore'.

**Comment by NoahAndrews** [comment]
The 3rd-party hosting service we were using for 6.0 artifacts (called Bintray) was shut down. Update your project to version 6.2, and that will work.

**Comment by NoahAndrews** [comment]
7.0 is out now.

**Comment by Crossle86** [comment]
Thanks for the quick response and 7.0 notification.




On Mon, September 20, 2021 9:24 am, Noah Andrews wrote:
>
7.0 is out now.
>
> --
> You are receiving this
because you authored the thread.
> Reply to this email directly or
view it on GitHub:
>
https://github.com/FIRST-Tech-Challenge/FtcRobotController/issues/154#issuecomment-923080726


Richard Corn
Software Devices LLC
P.O. Box 12299, Olympia WA. 98508
***@***.***Â Â Â www.swdevs.com
