### ISSUE TITLE
historic tensorflow and vuforia assets still included

### ISSUE THREAD

**Issue by thoughtless42** [FIRST-Tech-Challenge/FtcRobotController#165]
Is it possible to remove FtcRobotController/FtcRobotController/src/main/assets/  and FtcRobotController/tree/master/doc/media for the next release ? this will help the teams that use android studio by reducing the apk file size?

**Comment by cmacfarl** [comment]
You can remove them from you local clone via git rm if you like.  If you maintain a fork of FtcRobotController for team collaboration you can remove them from your fork.  No changes to those files are anticipated so your fetch/merge cycles should be seamless.
