### ISSUE TITLE
Problem with "create variable" in blocks (rev 6.0)

### ISSUE THREAD

**Issue by tjhawkey** [FIRST-Tech-Challenge/FtcRobotController#18]
Hmm. Clicking on "create variable" doesn't do anything. I'm using the rev hardware client. All versions (DS, all control hub) are latest as of 10/3. 
Even in some of the canned op modes with existing variables I can't create new.

**Comment by NoahAndrews** [comment]
This is a known issue, but thanks for reporting it. You can work around it by accessing Blocks from a web browser, instead of through the REV Hardware Client. The issue will be fixed in a future version of the Robot Controller app.

**Comment by NoahAndrews** [comment]
This can be solved by updating to Robot Controller version 6.1.
