### ISSUE TITLE
Add support for Windows Subsystem For Android.

### ISSUE THREAD

**Issue by frizelr4927** [FIRST-Tech-Challenge/FtcRobotController#214]
### This is not so much an issue, more an enhancement.

Currently it is possible to install APK files on the latest WSA preview version. Upon installing FTC Driver Station, it breifly flashes the window but then closes. This could be a WSA limitation, but seems to be because of an earlier issue involving the way Driver Station handles devices without USB support. That is however, just an educated guess. WSA is just an emulation of android.

### Some things to note:
- WSA is running Android 11
- At the time of writing I have only tested this on WSA version RD2A.210905.003
- Windows Build is 22483.rs_prerelease.211015-1431

This would be a useful addition to FTC because then we wouldn't need to buy phones and other acessories for the phones and just run it straight off the laptop. 

### Relevant Information:

https://docs.microsoft.com/en-us/windows/android/wsa/

Thanks,

Levi.

**Comment by Windwoes** [comment]
> Currently there are two pairing methods, "**Wi-Fi Direct**" and "**Control Hub**".  
> 
> I suggest a third pairing method, say "**TCP**" or "**Debug**", meaning a TCP/adb connection from the Driver Station to the Robot Controller. 
> 
> A new "TCP" pairing method might be an easier and more stable path than trying to get P2P working in WSA or other Virtual Machines.

It would actually need to be UDP. The RC/DS communication uses UDP.

**Comment by qwertychouskie** [comment]
I think https://acmerobotics.github.io/ftc-dashboard/ is probably a better solution for most computer users, it provides more features too.

**Comment by kevinfrei** [comment]
> I think https://acmerobotics.github.io/ftc-dashboard/ is probably a better solution for most computer users, it provides more features too.

Yeah, it's only missing the ability to do very peripheral things like *drive* the robot 🤣

**Comment by alan412** [comment]
You can use gamepads with ftc-dashboard and run your opmodes.   While it is
not the same latency, it is typically pretty good for testing subsystems.

--Alan
