### ISSUE TITLE
make sure to make PUBLIC!!!!!

### ISSUE THREAD

**Issue by sssssssssnake** [FIRST-Tech-Challenge/FtcRobotController#231]
https://github.com/sssssssssnake/FtcRobotController/blob/982386781b6769e08ace9a29ce51a2ab8d801bf0/TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Full.java#L13

**Comment by NoahAndrews** [comment]
I think you meant to post this on your fork, not the main repo.

**Comment by sssssssssnake** [comment]
Yeah Sorry!!!! I'm relatively new to Github :|

**Comment by sssssssssnake** [comment]
Yeah Sorry!!!! I'm relatively new to Github :|
