### ISSUE TITLE
Blocks can't call java method that has a VuforiaLocalizer parameter

### ISSUE THREAD

**Issue by lizlooney** [FIRST-Tech-Challenge/FtcRobotController#260]
If a team wanted to create a myBlock to set webcam exposure and gain, they'd need the java method to have a VuforiaLocalizer parameter so it can get the camera. However, there's no way in blocks to get the VuforiaLocalizer from the VuforiaFreightFrenzy blocks.

**Comment by NoahAndrews** [comment]
Fixed in 7.1.
