### ISSUE TITLE
Any way of adjusting Dualshock controller light strip through the SDK?

### ISSUE THREAD

**Issue by AndrewDTR** [FIRST-Tech-Challenge/FtcRobotController#306]
My apologies if this is the wrong place to ask this -- couldn't find any other resources or information anywhere else and I'm not sure if it's even a possibility.

**Comment by Windwoes** [comment]
Currently the light bar color is exclusively managed from the Driver Station, where it is tied to indicating driver position.

Supporting the ability for user code to control the color was considered, but at the time was decided against, for the reasons that 1) Having the light bar color always indicate driver position is good for clarity, and 2) Drivers are usually watching the robot, not looking at the gamepad, so rumble is probably a better choice for feedback in most circumstances.
