### ISSUE TITLE
Dimension Error in org.firstinspires.ftc.robotcore.external.matrices.MatrixF.inverted() method

### ISSUE THREAD

**Issue by ftcteam8397** [FIRST-Tech-Challenge/FtcRobotController#316]
For a 4x4 input matrix, this method returns a 4x4 matrix as expected. Likewise, for a 3x3 input matrix, it returns a 3x3 matrix. But for input matrices that are 2x2 or 1x1, this method returns a 4x4 matrix (filling in only the upper left 2x2 or 1x1 entries).

This causes a problem when one needs to continue with matrix math operations on the result. For example, if P and R are both 2x2 matrices, the following will throw an exception:

MatrixF K = P.multiplied(P.added(R).inverted);

**Comment by NoahAndrews** [comment]
Good catch, thank you.

**Comment by NoahAndrews** [comment]
This will be fixed in the next release.

**Comment by Windwoes** [comment]
Fixed in v7.2.
