### ISSUE TITLE
For 7.2: Changes needed in javadoc comments to match renaming of examples

### ISSUE THREAD

**Issue by alan412** [FIRST-Tech-Challenge/FtcRobotController#326]
In file /FtcRobotController/src/main/java/org/firstinspires/ftc/robotcontroller/external/samples/ConceptVuMarkIndentification.java:
Lines 52, 56, and 65 need to change to "ConceptVuforiaFieldNavigation"

In file /FtcRobotController/src/main/java/org/firstinspires/ftc/robotcontroller/external/samples/ConceptVuMarkIndentificationWebcam.java:
Lines 53, 57, and 66 need to change to "ConceptVuforiaFieldNavigationWebcam"

**Comment by gearsincorg** [comment]
Thanks for pointing this out.  I'll take care of it.

**Comment by NoahAndrews** [comment]
This was fixed in 8.0.
