### ISSUE TITLE
Auto-close PRs with only changes to the TeamCode folder

### ISSUE THREAD

**Issue by jasonappah** [FIRST-Tech-Challenge/FtcRobotController#33]
Just to prevent people from making a PR here with their team's code, we could set up a GitHub action to close PRs where the only files changed are in the TeamCode folder. We could also probably add a comment linking to `CONTRIBUTING.md` since it has a couple useful guides to Git.

**Comment by cmacfarl** [comment]
We've considered just auto-closing everything over the years as has been stated elsewhere the release model for the SDK doesn't have a provision for accepting PRs on the public repo.   My personal view on auto-closing is that it's not really necessary as I don't mind closing PRs manually for those that remain open, and for those that are closed by the original requestor, it's just a learning experience.   That said, auto-close is continually on the radar and it may be added in the future.  Thanks for the comments.
