### ISSUE TITLE
Cannot resolve symbol 'OpModeManagerImpl'

### ISSUE THREAD

**Issue by baqwas** [FIRST-Tech-Challenge/FtcRobotController#352]
Hello!

I read the Release note regarding **OpModeManagerImpl** and changed the import statement as required for 8.0. Unfortunately, the import declaration has OpModeManagerImpl still highlighted in red. Git commit generates a corresponding error that it cannot resolve the symbol. However, I am able to BUILD SUCCESFULly and deploy without any issue. Is there something that I can do to suppress the red highlight?

Regards.

**Comment by NoahAndrews** [comment]
Try restarting Android Studio, or selecting Invalidate Caches And Restart from the menus.

**Comment by baqwas** [comment]
Thanks @NoahAndrews! It worked but pardon my ignorance.

Kind regards.
