### ISSUE TITLE
Best android version for FTC SW testing?

### ISSUE THREAD

**Issue by wangxdflight** [FIRST-Tech-Challenge/FtcRobotController#396]
Due to limit access to control hub, we are using android phones for early development, especially for vision tasks.
Just wondering what the best android version to run FTC Robot controller?
From my experiences, android 7/8 on my pixel works well, but android 10 seems to have wifi direct issue causing robot controller restarting issue. I had to power off/on wifi so that Robot controller can be re-started.

**Comment by texasdiaz** [comment]
The control hub uses Android 7.1 - if you're looking for a comparable Android version, that would be it.
