### ISSUE TITLE
Where is the"PowerPlay.tflite" file

### ISSUE THREAD

**Issue by enterlight** [FIRST-Tech-Challenge/FtcRobotController#398]
If the team prefers using the pre trained model like in `java/org/firstinspires/ftc/robotcontroller/external/samples/ConceptTensorFlowObjectDetectionWebcam.java` there is no model file in the assets for it.  The  `PowerPlay.tflite` is missing from the source...

**Comment by cmacfarl** [comment]
Game assets are distributed as an artifact from MavenCentral.

You can find it in the AAR here: https://search.maven.org/artifact/org.firstinspires.ftc/gameAssets-PowerPlay
