### ISSUE TITLE
Rookie teams can't use IMU in new Control Hubs

### ISSUE THREAD

**Issue by alan412** [FIRST-Tech-Challenge/FtcRobotController#474]
The new Control Hubs have the new IMU: BHI260AP which is supposed to be supported in 8.1.    This is keeping rookie teams from being able to use the IMU.   (This is commonly used for field relative mecanum driving)

Please make available even a branch with that support early as scrimmages and competitions are coming.

Thanks,

Alan

**Comment by worthp** [comment]
I just found the same thing. Is there an ETA on that driver.?

**Comment by texasdiaz** [comment]
We are anticipating being able to release 8.1 early next week.

**Comment by worthp** [comment]
Excellent, @texasdiaz!!! Thanks for the quick reply.

**Comment by NoahAndrews** [comment]
8.1 is now live. See this tutorial for more details: https://ftc-docs.firstinspires.org/programming_resources/imu/imu.html

**Comment by worthp** [comment]
Whooo hooo!!! I"ll check it out tmrw and keep you posted.Thanks againOn Nov 21, 2022 8:03 PM, Noah Andrews ***@***.***> wrote:
8.1 is now live. See this tutorial for more details: https://ftc-docs.firstinspires.org/programming_resources/imu/imu.html

**Comment by worthp** [comment]
@NoahAndrews i updated robot and drive station. new one is working as expected. thanks again for the quick turn and communication!
