### ISSUE TITLE
TFOD inference time/latency?

### ISSUE THREAD

**Issue by wangxdflight** [FIRST-Tech-Challenge/FtcRobotController#501]
We saw latency more than 1 second. Is it expected?
Possible to make it run faster?

There are some parameters for TFOD. Not sure anyone has tried to modify them.

    public boolean isModelQuantized = true;
    public int inputSize = 300; // px
    public int numInterpreterThreads = 1;
    public int numExecutorThreads = 2;
    public int maxNumDetections = 10;

    @Deprecated
    public int timingBufferSize = 10;

    @Deprecated
    public double maxFrameRate = 30;

    public float minResultConfidence = 0.4f;
    public float trackerMaxOverlap = 0.2f;
    public float trackerMinSize = 16.0f;
    public float trackerMarginalCorrelation = 0.75f;
    public float trackerMinCorrelation = 0.3f;

Thanks.

**Comment by texasdiaz** [comment]
You'll find that tweaking parameters for TFOD won't help our use-case - we don't/can't use multiple interpreters, our hardware can't handle it, and that's usually how you speed things up (throw images into more pipelines to do inference in parallel). The inference processing on the Control Hub or a legal FTC phone literally cannot get any faster - the only real thing you can do is enable tracking on the FTC API side to help track objects between inference detections; this way you can get ~15fps or more tracking once an object is identified/detected.

**Comment by wangxdflight** [comment]
Thanks for the reply. We noticed that it was faster after an object was detected.
The processor on control hub is indeed not so powerful.

![image](https://user-images.githubusercontent.com/229830/204665722-5bffcfe3-e52c-44fa-b5d3-c1642270d8df.png)

**Comment by texasdiaz** [comment]
Yep, the challenge we face in defining the next "Revision" of the Control Hub is chip lifetimes, most processors for mobile devices have a lifespan of 1-2 years whereas we want 5+ years. So in our long-term roadmap planning we're looking at these kinds of things with an eye toward the future of FTC hardware!
