### ISSUE TITLE
Create New Op Mode Failed Error Code 0 on v8.1.1

### ISSUE THREAD

**Issue by JohnDNC** [FIRST-Tech-Challenge/FtcRobotController#525]
I just installed v8.1.1.  Everything has been restarted and turned off +on multiple times. 
Firefox browser cache was cleared.
Every time I try this it fails with message "New project failed. Error Code 0"
Create new Op Mode Name: TestREVColorDistance  Sample: SensorREVColorDistance.
It also fails the same way with Sample: BasicOpMode
We're using Blocks

**Comment by JohnDNC** [comment]
I am very new +green on this FTC.
This is my first hands-on session working on our autonomous program.
In general we have, two motors driving the four drive wheels.
We do have the REVColorDistance sensor installed and mostly working.  We
had the issue of too much green detected.

I need to create some test OpModes to understand how Blocks plus each of
the REVColorDistance sensor and the IMU work.

I should be able to send config files, logs, etc, if you can give some
hints on how to get them.

**Comment by WestsideRobotics** [comment]
At your programming screen, please click the top-level tab called `Manage`.  What does the top line say?

**Comment by JohnDNC** [comment]
It says Robot Controller version: 8.1
Control Hub version: 1.1.3
REV Hubs:
Control Hub Firmware version: 1.8.2
IMU: BHI260AP

Expansion Hub 3
Firmware version: 1.8.2
IMU: BNO055

**Comment by WestsideRobotics** [comment]
The first line says that you have not actually updated the RC app to 8.1.1, you are still at 8.1.

**Comment by JohnDNC** [comment]
Yes, I can't explain that.
On our driver display device, it showed Update to 8.1.1 earlier tonight. I did that while connected to my home wifi.
It now shows "Software Manager - All applications up to date as of 1 hour ago.
The FTC Driver Station About shows App Version 8.1.1

Is there a link to instructions for what I need to do to get Robot Controller version up from 8.1 to 8.1.1 ?

**Comment by cmacfarl** [comment]
There are two devices at play here.  Your Driver Station, which appears to be updated to 8.1.1 and your Robot Controller, which I'll assume is a Control Hub, which is still at 8.1.    The Blocks software runs on the Control Hub, not the Driver Station. 

You need to connect the Control Hub via USB to a laptop with the REV Hardware Client application installed.  The Hardware Client should then recognize the Control Hub and give you the option to update it.  If it does not, please provide screen shots.

**Comment by cmacfarl** [comment]
> Is there a link to instructions for what I need to do to get Robot Controller version up from 8.1 to 8.1.1 ?

https://docs.revrobotics.com/duo-control/control-hub-gs/connect-to-the-control-hub-robot-control-console

**Comment by WestsideRobotics** [comment]
The official FTC updating instruction are [**here**](http://ftc-docs.firstinspires.org/ftc_sdk/updating/index.html).

Download the REV Hardware Client [**here**](https://docs.revrobotics.com/rev-hardware-client/).

Good luck, and welcome to FTC!

**Comment by JohnDNC** [comment]
Thanks for your help +patience.
I'll try those instructions and update here later.

**Comment by JohnDNC** [comment]
I am confirming that after updating the Robot Controller h/w to 8.1.1 this works as expected.
