### ISSUE TITLE
Getting Error: BUSY on pair

### ISSUE THREAD

**Issue by citricacid2** [FIRST-Tech-Challenge/FtcRobotController#58]
Whenever we try to connect the driver station to the robot controller, there is a network error busy that appears.

The pairing was working fine earlier.

**Comment by FROGbots-4634** [comment]
Which phones are you using?

**Comment by citricacid2** [comment]
I solved this problem by forgetting all known WiFi networks on the driver station, thank you @FROGbots-4634 for trying to help.
