### ISSUE TITLE
Legal for dark mode in competitions?

### ISSUE THREAD

**Issue by JackTheFine** [FIRST-Tech-Challenge/FtcRobotController#582]
Im a coder for my team and to make the rc screen better on our eyes we make the screen dark and recolored the text so we can see it. Is this competition legal?
![](https://i.gyazo.com/a3326f8532eb63748b3eb53b18b74fb0.png)

**Comment by cmacfarl** [comment]
Game and competition legality rules can only answered at https://ftc-qa.firstinspires.org.

Please ask the question there.
