### ISSUE TITLE
UG Training Dataset

### ISSUE THREAD

**Issue by ssysm** [FIRST-Tech-Challenge/FtcRobotController#6]
Is it possible to release the original dataset used to train the TFLite model for detecting the rings?

Thanks in advance.

**Comment by cmacfarl** [comment]
It is not possible to release the original datasets.  They are produced in people's offices, homes, workshops, etc and are not sanitized for potentially sensitive information in the background.

**Comment by ssysm** [comment]
Understandable. Thanks for updating on this.
