### ISSUE TITLE
New IMU API angular velocity wraps around

### ISSUE THREAD

**Issue by rbrott** [FIRST-Tech-Challenge/FtcRobotController#617]
I have an op mode that essentially calls `imu.getRobotAngularVelocity(AngleUnit.RADIANS)` in a loop as voltage applied to the motors slowly ramps. Here's the plot:
![image](https://user-images.githubusercontent.com/6677314/222332354-81b7d69e-dda6-4343-a3f8-966c5470e75a.png)
I wouldn't expect the **velocity** here to wrap around.

I haven't had the chance to investigate in detail. I'm not sure if the issue is with the imu -> robot transform or is with the hardware (I'm actually not sure if this data is from a BNO or BHI).

**Comment by gearsincorg** [comment]
Yes.  Weird that it seems to be wrapping at PI.  Might be normal for angle, but not angular velocity.

**Comment by Windwoes** [comment]
This was fixed in v10.0
