### ISSUE TITLE
I2CDeviceSynch for serial communications

### ISSUE THREAD

**Issue by Team14423** [FIRST-Tech-Challenge/FtcRobotController#63]
Hi -

We are trying to implement PixyCam2, which uses I2C, but does not use registers. Is there a parameter we can send in for ireg that will cause read() and write() to behave like serial drivers, simply reading data off the port as it comes rather than listing a specific register?

If not, is this why people say to use LegoI2C mode? If so, do you know the register we use for that?

**Comment by FROGbots-4634** [comment]
Duplicate of https://github.com/ftctechnh/ftc_app/issues/577

**Comment by Team14423** [comment]
Awwww, I got so excited thinking it was fixed. So, there's no solution on this point?

**Comment by Windwoes** [comment]
This will be fixed in the next version of the SDK.

**Comment by Team14423** [comment]
Awesome - thank you!

**Comment by Windwoes** [comment]
Fixed in v7.0
