### ISSUE TITLE
Broken links in README

### ISSUE THREAD

**Issue by dansman805** [FIRST-Tech-Challenge/FtcRobotController#66]
The link to "FTC Javadoc Documentation" under [Javadoc Reference Material](https://github.com/FIRST-Tech-Challenge/FtcRobotController#javadoc-reference-material) in the README is broken. It links to https://first-tech-challenge.github.io/FtcRobotController/doc/javadoc/index.html, which leads to a 404 page. It should probably point to https://first-tech-challenge.github.io/FtcRobotController/. Sidenote, the documentation there is for version 6.0 of the SDK: this should be updated to 6.1.

The link to the "FTC Technology Forum" under [Online User Forum](https://github.com/FIRST-Tech-Challenge/FtcRobotController#online-user-forum) in the README points to https://ftcforum.usfirst.org/forumdisplay.php?156-FTC-Technology, which seemingly loads forever. It should likely point to https://ftcforum.firstinspires.org/forum/ftc-technology.

**Comment by CalKestis** [comment]
Fixed by #68
