### ISSUE TITLE
Tag Filtering Bug in RobotAutoDriveToAprilTag Samples

### ISSUE THREAD

**Issue by abidingabi** [FIRST-Tech-Challenge/FtcRobotController#667]
Both the [tank](https://github.com/FIRST-Tech-Challenge/FtcRobotController/blob/660a2f63bc04c25ee3b405ca03aa2cb34194ede8/FtcRobotController/src/main/java/org/firstinspires/ftc/robotcontroller/external/samples/RobotAutoDriveToAprilTagTank.java) and [omni](https://github.com/FIRST-Tech-Challenge/FtcRobotController/blob/660a2f63bc04c25ee3b405ca03aa2cb34194ede8/FtcRobotController/src/main/java/org/firstinspires/ftc/robotcontroller/external/samples/RobotAutoDriveToAprilTagOmni.java) RobotAutoDriveToAprilTag Sample OpModes allow the user to set `DESIRED_TAG_ID`, with the comment “Choose the tag you want to approach or set to -1 for ANY tag”.

However, setting `DESIRED_TAG_ID` to `-1` does not allow any tag; looking at the [detection filtering code](https://github.com/FIRST-Tech-Challenge/FtcRobotController/blob/660a2f63bc04c25ee3b405ca03aa2cb34194ede8/FtcRobotController/src/main/java/org/firstinspires/ftc/robotcontroller/external/samples/RobotAutoDriveToAprilTagOmni.java#L154) (which is the same across both opmodes), this is because the check for `DESIRED_TAG_ID` being negative is inverted.

The current condition is:
```java
(detection.metadata != null) && ((DESIRED_TAG_ID >= 0) || (detection.id == DESIRED_TAG_ID))  
```
while it likely should be:
```java
(detection.metadata != null) && ((DESIRED_TAG_ID < 0) || (detection.id == DESIRED_TAG_ID))  
```

**Comment by gearsincorg** [comment]
Great catch.  We’ll fix that ASAP
