### ISSUE TITLE
ConceptAprilTag suggests you use VisionPortal.Builder()#enableCameraMonitoring which doesn't exist

### ISSUE THREAD

**Issue by Attack8** [FIRST-Tech-Challenge/FtcRobotController#676]
Should be changed to VisionPortal.Builder()#enableLiveView

Effects at least 
RobotAutoDriveToAprilTagOmni
RobotAutoDriveToAprilTagTank
ConceptAprilTag
ConceptAprilTagEasy

There may be more but I couldn't find them

**Comment by gearsincorg** [comment]
Thanks for reporting that.

The method name was changed late in the game, and it looks like the refactor didn't hit the comments.
The only two samples that I could find that are effected are:

ConceptAprilTag.java
ConceptTensorFlowObjectDetection.java

We'll take care of it.

**Comment by Attack8** [comment]
Ok! Thanks!

**Comment by lizlooney** [comment]
This has been fixed and will be in the next release. I don't know when that will be.
