### ISSUE TITLE
Out-of-bounds access in libuvc

### ISSUE THREAD

**Issue by qwertychouskie** [FIRST-Tech-Challenge/FtcRobotController#683]
https://github.com/libuvc/libuvc/pull/211

Would be good to get this fix included in the SDK's copy of `libuvc`.  We hit an intermittent low-level crash last season when using 3 cameras, and this seems to be the most likely cause.

**Comment by Windwoes** [comment]
The use of libuvc in the SDK does not include the uvc_yuyv2bgr() function to my knowledge, though I'd have to do a reference search to be sure. The raw yuyv or mjpeg buffer is handed to EasyOpenCV, where it is handed to either OpenCV to do the conversion to RGBA (in the case of yuy2) or to libjpeg-turbo (in the case of mjpeg).
