### ISSUE TITLE
Cannot turn off Fps meter on display viewport.

### ISSUE THREAD

**Issue by trc492** [FIRST-Tech-Challenge/FtcRobotController#707]
For last season, you can turn off FpsMeter by calling OpenCvCamera.showFpsMeterOnViewport(false). With the new VisionPortal, you no longer have access to OpenCvCamera. Therefore, it is not easy to turn off the FpsMeter that blocks a substantial area of the lower left corner of the viewport.

**Comment by Windwoes** [comment]
This will be fixed in the next release of the FTC SDK.

**Comment by Windwoes** [comment]
Fixed in v9.1
