### ISSUE TITLE
Gyro Support for Gamepads

### ISSUE THREAD

**Issue by j5155** [FIRST-Tech-Challenge/FtcRobotController#838]
The PlayStation 4 and 5 controllers support gyroscope and accelerometer based input, however the FIRST SDK appears to not be able to access it. Our team would like to explore gyro based controls because we believe the absolute aspects could be extremely helpful but this stops us from doing so. We would really appreciate it being implemented!

**Comment by Windwoes** [comment]
Duplicate of https://github.com/FIRST-Tech-Challenge/FtcRobotController/issues/649

**Comment by j5155** [comment]
> Duplicate of #649

That issue seems to have been closed by the author before it was implemented. Can it be reopened?

**Comment by j5155** [comment]
Closed as duplicate of #649 as it has reopened.
