### ISSUE TITLE
Size import missing in certain samples that use VisionPortal.setCameraResolution()

### ISSUE THREAD

**Issue by CalKestis** [FIRST-Tech-Challenge/FtcRobotController#946]
Applies to v9.0.1 and earlier.

Certain samples contain a commented out line that calls VisionPortal.setCameraResolution(Size cameraResolution).  If this line uncommented, and you are using OnBot Java for development, the build will break because OnBot Java will not auto import the Size class, and the sample is not shipped with the Size be default in its list of import statements.

To fix the problem simply add
```
import android.util.Size;
```
to the list of existing imports at the top of the file.

v9.1 has the necessary import added by default.

**Comment by gearsincorg** [comment]
This issue has been corrected in in 9.10.  

The Size import has been included in all sampes that include it int the code, or in commented out samples.
