### ISSUE TITLE
Android Studio Driver Station App Keeps Deleted OpModes

### ISSUE THREAD

**Issue by YourAverageFTCPerson** [FIRST-Tech-Challenge/FtcRobotController#958]
After I deleted all Blocks and OnBot Java OpModes from 192.168.43.1:8080, the Android Studio robot controller app kept them there. It wasn't a visual glitch from 192.168.43.1:8080 because REV Hardware Client also showed that there were no OnBot Java or Blocks OpModes. And no, I haven't tried running these ghost OpModes because I currently don't have my robot and when I did I ran out of time to try.

**Comment by Windwoes** [comment]
After deleting OBJ OpModes, you need to run a build.

**Comment by YourAverageFTCPerson** [comment]
I'm sorry for wasting your time.
