### ISSUE TITLE
Custom Robot Controller instead of RoboRIO

### ISSUE THREAD

**Issue by maxxlife** [FIRST-Tech-Challenge/FtcRobotController#989]
Hello,
I might have a noob question, but can I use some single-board computer with GPIO and CAN-bus instead of RoboRIO controller to build a FIRST robot?

**Comment by cmacfarl** [comment]
Wrong repository.  

This repository manages software for FTC and runs on an Android based REV Control Hub.

The RoboRIO is the device used on FRC robots and runs WPILib software.  See: https://github.com/wpilibsuite
