### ISSUE TITLE
REV Controller won't vibrate or have touchpad function

### ISSUE THREAD

**Issue by greenbear26** [FIRST-Tech-Challenge/FtcRobotController#999]
I recently bought the new REV controller that was advertised with rumble functionality and touchpad control, like a PS4 controller would. However, when running the test opmodes for rumble and touchpad on the latest version, it wouldn't work. This is strange because version 9.2 notes say that it added REV controller compatibility. I assume it has a similar type to a PS4 controller behind the scenes, but I am unable to locate the code adding this functionality.

**Comment by Windwoes** [comment]
Do you have advanced gamepad features enabled in the settings?

**Comment by greenbear26** [comment]
No, what is that?

**Comment by Windwoes** [comment]
It's an option in the settings on the Driver Station app.

**Comment by greenbear26** [comment]
Ok, after doing that I realized that I hadn't updated the robot controller app and driver station app, so I did that and now it works. Thanks for the help!
